---

optimizee-type: LASSO
input-dim: 40
output-dim: 20
sparsity: 5

optimizer: GOMathL2O
lstm-layers: 2
lstm-hidden-size: 20
grad-method: smooth_grad

r-use: false
r-scale: 1.0
r-scale-learned: false
r-norm: sigmoid

q-use: false
q-scale: 1.0
q-scale-learned: false
q-norm: sigmoid

h-use: false
h-scale: 1.0
h-scale-learned: false
h-norm: sigmoid

a-use: false
a-scale: 1.0
a-scale-learned: false
a-norm: sigmoid1

b-use: false
b-scale: 1.0
b-scale-learned: false
b-norm: sigmoid1

c-use: false
c-scale: 1.0
c-scale-learned: false
c-norm: sigmoid1

b3-use: false
b3-scale: 1.0
b3-scale-learned: false
b3-norm: sigmoid1

b4-use: false
b4-scale: 1.0
b4-scale-learned: false
b4-norm: sigmoid1

b5-use: false
b5-scale: 1.0
b5-scale-learned: false
b5-norm: sigmoid1

save-dir: "LASSO-toy"

device: cuda:0

init-lr: 1e-2
global-training-steps: 500
optimizer-training-steps: 100
unroll-length: 20
train-batch-size: 64

val-size: 512
val-freq: 20
val-length: 100

print-freq: 20

test-length: 100
test-size: 1024
test-batch-size: 32
loss-save-path: losses-toy

# step-size: 1e-4
momentum1: 1e-4
momentum2: 1e-4
eps: 1e-8
hyper-step: 1e-7
