---

optimizee-type: LASSO
input-dim: 500
output-dim: 250
sparsity: 50

optimizer: GOMathL2O
lstm-layers: 2
lstm-hidden-size: 20
grad-method: smooth_grad

r-use: false
r-scale: 1.0
r-scale-learned: false
r-norm: sigmoid

q-use: false
q-scale: 1.0
q-scale-learned: false
q-norm: sigmoid

b-use: false
b-scale: 1.0
b-scale-learned: false
b-norm: sigmoid1

b3-use: false
b3-scale: 1.0
b3-scale-learned: false
b3-norm: sigmoid1

b4-use: false
b4-scale: 1.0
b4-scale-learned: false
b4-norm: sigmoid1


B-step-size: "B"
C-step-size: "C"

save-dir: "LASSO"

device: cuda:1

init-lr: 1e-2
global-training-steps: 500
optimizer-training-steps: 100
unroll-length: 20
train-batch-size: 128
scheduler: "step"
clip-grad: true

val-size: 512
val-freq: 20
val-length: 100

print-freq: 20

epochs: 3

loss-func: "mean"