---

optimizee-type: LogisticL1
input-dim: 50
output-dim: 1000
sparsity: 20
rho: 0.1

optimizer: GOMathL2O
lstm-layers: 2
lstm-hidden-size: 20
grad-method: smooth_grad

r-use: false
r-scale: 1.0
r-scale-learned: false
r-norm: softplus

q-use: false
q-scale: 10.0
q-scale-learned: false
q-norm: softplus

b-use: false
b-scale: 1.0
b-scale-learned: false
b-norm: softplus

b3-use: false
b3-scale: 1.0
b3-scale-learned: false
b3-norm: softplus

b4-use: false
b4-scale: 1.0
b4-scale-learned: false
b4-norm: softplus

B-step-size: "B"
C-step-size: "C"

state-scale: 1

save-dir: "LogisticL1"

device: cuda:1

test: true
test-length: 1000
test-size: 1024
test-batch-size: 32
loss-save-path: losses-rand

momentum1: 1e-4
momentum2: 1e-4
eps: 1e-8
hyper-step: 1e-7

